-- SCRIPT PARA CRIACAO DO BANCO DE DADOS E DAS TABELAS

-- sudo -i -u postgres
-- psql -f /PATH/script.sql

DROP DATABASE academico;
CREATE DATABASE academico;

\c academico

CREATE TABLE USUARIO (
	COD_USER		SERIAL				NOT NULL, 
	NOMECOMPLETO	VARCHAR(30)			NOT NULL, 
	IDADE			INT					NOT NULL, 
	DATADEINGRESSO	DATE				NOT NULL, 
	LATTES			VARCHAR(50)			NOT NULL, 
PRIMARY KEY (COD_USER)
);

CREATE TABLE PROFESSOR (
	COD_PROF		INT					NOT NULL, 
	DEPARTAMENTO	VARCHAR(30)					, 
FOREIGN KEY (COD_PROF) REFERENCES USUARIO (COD_USER)
);

CREATE TABLE ALUNO (
	COD_ALUNO		INT					NOT NULL, 
	NOMECURSO		VARCHAR(50)			NOT NULL, 
	MATRICULA		VARCHAR(8)			NOT NULL, 
	POSSUIBOLSA		BOOLEAN				NOT NULL,
	TIPOBOLSA		VARCHAR(30)					,
	VALORBOLSA		REAL						,
FOREIGN KEY (COD_ALUNO) REFERENCES USUARIO (COD_USER)
);

CREATE TABLE EFETIVO(
	COD_PROF_E		INT					NOT NULL,  
	NOMECURSO		VARCHAR(50)			NOT NULL, 
FOREIGN KEY (COD_PROF_E) REFERENCES USUARIO (COD_USER)
);

CREATE TABLE COLABORADOR(
	COD_PROF_C		INT					NOT NULL, 
	DATATERMINO		DATE				NOT NULL, 
	UNIORIGEM		VARCHAR(30)			NOT NULL, 
FOREIGN KEY (COD_PROF_C) REFERENCES USUARIO (COD_USER)
);

CREATE TABLE POSGRADUACAO(
	COD_ALUNO_POS	INT					NOT NULL, 
	DESCRIPOS		VARCHAR(200)		NOT NULL, 
	TIPPOS			VARCHAR(30)			NOT NULL, 
FOREIGN KEY (COD_ALUNO_POS) REFERENCES USUARIO (COD_USER)
);

CREATE TABLE GRADUACAO(
	COD_ALUNO_GRAD	INT					NOT NULL, 
	DATADEINGRESSO	DATE				NOT NULL, 
	TIPOINGRE		VARCHAR(30)			NOT NULL, 
FOREIGN KEY (COD_ALUNO_GRAD) REFERENCES USUARIO (COD_USER)
);

CREATE TABLE EVENTO(
	CODIGOEVENTO	SERIAL				NOT NULL,
	NOMEVENTO		VARCHAR(30)			NOT NULL,
	LOCAL			VARCHAR(30)			NOT NULL,
	DATA			DATE				NOT NULL,
	EDICAO			INT					NOT NULL,
PRIMARY KEY (CODIGOEVENTO)
);

CREATE TABLE AREAPESQUISA(
	NOME_PESQS		VARCHAR(30)			NOT NULL, 
	DESCRI			VARCHAR(200)		NOT NULL,
PRIMARY KEY (NOME_PESQS) 
);

CREATE TABLE AREATUACAO(
	NOME_ATUA		VARCHAR(30)			NOT NULL, 
	DESCRI			VARCHAR(200)		NOT NULL, 
	FERRAMENTAS		VARCHAR(100)		NOT NULL,
PRIMARY KEY (NOME_ATUA)
);

CREATE TABLE TRABALHOS(
	CODIGOTRABALHO	SERIAL				NOT NULL, 
	TITULO			VARCHAR(50)			NOT NULL,
	DATACONCLUSAO	DATE				NOT NULL,
	AUTORES			VARCHAR(50)			NOT NULL,
	IDIOMA			VARCHAR(50)			NOT NULL,
PRIMARY KEY (CODIGOTRABALHO)
);

CREATE TABLE MONOGRAFIA(
	CODIGOTRABALHO	INT					NOT NULL,
	DATADEDEFESA	DATE				NOT NULL, 
	TIPO			VARCHAR(30)			NOT NULL, 
FOREIGN KEY (CODIGOTRABALHO) REFERENCES TRABALHOS (CODIGOTRABALHO)
);

CREATE TABLE ARTIGOS(
	CODIGOTRABALHO	INT					NOT NULL,
	CODIGOEVENTO	INT					NOT NULL,
	STATUS			BOOLEAN				NOT NULL,
	DATADENVIO		DATE				NOT NULL,  
FOREIGN KEY (CODIGOTRABALHO) REFERENCES TRABALHOS (CODIGOTRABALHO),
FOREIGN KEY (CODIGOEVENTO) 	 REFERENCES EVENTO (CODIGOEVENTO)
);

CREATE TABLE ORIENTA(
	COD_ALUNO		INT					NOT NULL,
	COD_PROF		INT					NOT NULL,
FOREIGN KEY (COD_ALUNO) REFERENCES USUARIO (COD_USER),
FOREIGN KEY (COD_PROF)  REFERENCES USUARIO (COD_USER)
);

CREATE TABLE USUARIO_ATUA(
	COD_USER		INT					NOT NULL,
	NOME_ATUA		VARCHAR(30)			NOT NULL,
FOREIGN KEY (COD_USER)	REFERENCES USUARIO (COD_USER),
FOREIGN KEY (NOME_ATUA) REFERENCES AREATUACAO (NOME_ATUA)
);

CREATE TABLE USUARIO_PESQUISA(
	COD_USER		INT					NOT NULL,
	NOME_PESQS		VARCHAR(30)			NOT NULL, 
FOREIGN KEY (COD_USER) 	 REFERENCES USUARIO (COD_USER),
FOREIGN KEY (NOME_PESQS) REFERENCES AREAPESQUISA (NOME_PESQS)
);

CREATE TABLE USUARIO_EVENTO(
	COD_USER		INT					NOT NULL,
	CODIGOEVENTO	INT					NOT NULL,
FOREIGN KEY (COD_USER) REFERENCES USUARIO (COD_USER),
FOREIGN KEY (CODIGOEVENTO) REFERENCES EVENTO (CODIGOEVENTO)
);

CREATE TABLE USUARIO_TRABALHO(
	COD_USER		INT					NOT NULL,
	CODIGOTRABALHO	INT					NOT NULL,
FOREIGN KEY (COD_USER) 		 REFERENCES USUARIO (COD_USER),
FOREIGN KEY (CODIGOTRABALHO) REFERENCES TRABALHOS (CODIGOTRABALHO)
);

CREATE TABLE ATUACAO_TRABALHO(
	CODIGOTRABALHO	INT					NOT NULL,
	NOME_ATUA		VARCHAR(30)			NOT NULL, 
	FOREIGN KEY (CODIGOTRABALHO) REFERENCES TRABALHOS (CODIGOTRABALHO),
	FOREIGN KEY (NOME_ATUA) 	 REFERENCES AREATUACAO (NOME_ATUA)
);
