-- SCRIPT COM OPERACOES NO BANCO DE DADOS

\c academico


SELECT ALUNO.COD_ALUNO, ALUNO.NOMECURSO, ALUNO.TIPOBOLSA, USUARIO_PESQUISA.NOME_PESQS
FROM ALUNO, USUARIO_PESQUISA
WHERE ALUNO.TIPOBOLSA = 'FAPERGS' and COD_ALUNO = COD_USER;


SELECT ARTIGOS.CODIGOTRABALHO AS CODTRABALHO, EVENTO.NOMEVENTO AS EVENTO, TRABALHOS.TITULO AS TITULO
FROM ARTIGOS, TRABALHOS, EVENTO
WHERE ARTIGOS.CODIGOTRABALHO = TRABALHOS.CODIGOTRABALHO AND ARTIGOS.CODIGOEVENTO = EVENTO.CODIGOEVENTO;


SELECT A.NOMECOMPLETO AS Nome_Aluno, P.NOMECOMPLETO AS Nome_Orientador
FROM ORIENTA
JOIN (	SELECT USUARIO.COD_USER, USUARIO.NOMECOMPLETO
		FROM ALUNO JOIN USUARIO
		ON (ALUNO.COD_ALUNO = USUARIO.COD_USER)) AS A
ON   (ORIENTA.COD_ALUNO = A.COD_USER)
JOIN (  SELECT USUARIO.COD_USER, USUARIO.NOMECOMPLETO
		FROM PROFESSOR JOIN USUARIO
		ON (PROFESSOR.COD_PROF = USUARIO.COD_USER)) AS P
ON   (ORIENTA.COD_PROF = P.COD_USER)
ORDER BY ORIENTA.COD_ALUNO;


SELECT MONOGRAFIA.DATADEDEFESA AS DATA,TRABALHOS.TITULO AS TITULO, MONOGRAFIA.TIPO
FROM MONOGRAFIA, TRABALHOS
WHERE MONOGRAFIA.CODIGOTRABALHO = TRABALHOS.CODIGOTRABALHO
ORDER BY MONOGRAFIA.DATADEDEFESA DESC;


SELECT USUARIO.NOMECOMPLETO, USUARIO_ATUA.NOME_ATUA, USUARIO_PESQUISA.NOME_PESQS
FROM USUARIO_ATUA, USUARIO, USUARIO_PESQUISA
WHERE USUARIO_ATUA.COD_USER = USUARIO.COD_USER AND USUARIO_PESQUISA.COD_USER = USUARIO.COD_USER;